//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 04:53:40 PM WEST 
//


package com.lyncode.xoai.serviceprovider.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="resumptionInterval" type="{http://www.w3.org/2001/XMLSchema}int" default="1000" />
 *       &lt;attribute name="trustAllCertificates" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Configuration")
public class Configuration {

    @XmlAttribute
    protected Integer resumptionInterval;
    @XmlAttribute
    protected Boolean trustAllCertificates;

    /**
     * Gets the value of the resumptionInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getResumptionInterval() {
        if (resumptionInterval == null) {
            return  1000;
        } else {
            return resumptionInterval;
        }
    }

    /**
     * Sets the value of the resumptionInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResumptionInterval(Integer value) {
        this.resumptionInterval = value;
    }

    /**
     * Gets the value of the trustAllCertificates property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTrustAllCertificates() {
        if (trustAllCertificates == null) {
            return true;
        } else {
            return trustAllCertificates;
        }
    }

    /**
     * Sets the value of the trustAllCertificates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrustAllCertificates(Boolean value) {
        this.trustAllCertificates = value;
    }

}
