//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.dataprovider.xml.oaipmh;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * Java class for deletedRecordType.
 * 
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * 









 * 
 */
@XmlType(name = "deletedRecordType")
@XmlEnum
public enum DeletedRecordType {

	@XmlEnumValue("no")
	NO("no"), @XmlEnumValue("persistent")
	PERSISTENT("persistent"), @XmlEnumValue("transient")
	TRANSIENT("transient");
	private final String value;

	DeletedRecordType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static DeletedRecordType fromValue(String v) {
		for (DeletedRecordType c : DeletedRecordType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
