//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.dataprovider.xml.oaipmh;

import com.lyncode.xoai.dataprovider.exceptions.WritingXmlException;
import com.lyncode.xoai.dataprovider.xml.EchoElement;
import com.lyncode.xoai.dataprovider.xml.XMLWritable;
import com.lyncode.xoai.dataprovider.xml.XmlOutputContext;
import com.lyncode.xoai.dataprovider.xml.xoai.Metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * The descriptionType is used for the description element in Identify and for
 * setDescription element in ListSets. Content must be compliant with an XML
 * Schema defined by a community.
 *
 *
 * Java class for descriptionType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 *











 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "descriptionType")
public class DescriptionType implements XMLWritable {

    @XmlValue
    protected String value;

    private Metadata metadata;

    public DescriptionType() {
    }

    public DescriptionType(Metadata m) {
        metadata = m;
    }

    public DescriptionType(String m) {
        value = m;
    }

    /**
     * Gets the value of the any property.
     *
     * @return possible object is ;
     */
    public String getAny() {
        return value;
    }

    /**
     * Sets the value of the any property.
     *
     * @param value allowed object is ;
     */
    public void setAny(String value) {
        this.value = value;
    }

    public void setAny(Metadata metadata) {
        this.metadata = metadata;
    }

    @Override
    public void write(XmlOutputContext writer) throws WritingXmlException {
        if (metadata != null) {
            this.metadata.write(writer);
        } else if (this.value != null) {
            EchoElement echo = new EchoElement(value);
            echo.write(writer);
        }
    }

}
