//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.dataprovider.xml.oaipmh;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;

import com.lyncode.xoai.dataprovider.exceptions.WrittingXmlException;
import com.lyncode.xoai.dataprovider.xml.XMLWrittable;

/**
 * <p>
 * Java class for GetRecordType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GetRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="record" type="{http://www.openarchives.org/OAI/2.0/}recordType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRecordType", propOrder = { "record" })
public class GetRecordType implements XMLWrittable {

	@XmlElement(required = true)
	protected RecordType record;

	/**
	 * Gets the value of the record property.
	 * 
	 * @return possible object is {@link RecordType }
	 * 
	 */
	public RecordType getRecord() {
		return record;
	}

	/**
	 * Sets the value of the record property.
	 * 
	 * @param value
	 *            allowed object is {@link RecordType }
	 * 
	 */
	public void setRecord(RecordType value) {
		this.record = value;
	}

    @Override
    public void write(XMLStreamWriter writter) throws WrittingXmlException {
        try {
            writter.writeStartElement("record");
            if (this.record != null)
                this.record.write(writter);
            writter.writeEndElement();
        } catch (XMLStreamException e) {
            throw new WrittingXmlException(e);
        }
    }

}
