//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.dataprovider.xml.oaipmh;

import com.lyncode.xoai.dataprovider.exceptions.WritingXmlException;
import com.lyncode.xoai.dataprovider.xml.XMLWritable;
import com.lyncode.xoai.dataprovider.xml.XmlOutputContext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.stream.XMLStreamException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * Java class for ListIdentifiersType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 *












 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListIdentifiersType", propOrder = {"header",
        "resumptionToken"})
public class ListIdentifiersType implements XMLWritable {

    @XmlElement(required = true)
    protected List<HeaderType> header;
    protected ResumptionTokenType resumptionToken;

    /**
     * Gets the value of the header property.
     *
     *
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
      method for the header property.
     *
     *
     * For example, to add a new item, do as follows:
     *

     * getHeader().add(newItem);

     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * ;
     */
    public List<HeaderType> getHeader() {
        if (header == null) {
            header = new ArrayList<HeaderType>();
        }
        return this.header;
    }

    /**
     * Gets the value of the resumptionToken property.
     *
     * @return possible object is ;
     */
    public ResumptionTokenType getResumptionToken() {
        return resumptionToken;
    }

    /**
     * Sets the value of the resumptionToken property.
     *
     * @param value allowed object is ;
     */
    public void setResumptionToken(ResumptionTokenType value) {
        this.resumptionToken = value;
    }

    @Override
    public void write(XmlOutputContext context) throws WritingXmlException {
        try {
            if (this.header != null && !this.header.isEmpty()) {
                for (HeaderType header : this.header) {
                    context.getWriter().writeStartElement("header");
                    header.write(context);
                    context.getWriter().writeEndElement();
                }
            }

            if (this.resumptionToken != null) {
                context.getWriter().writeStartElement("resumptionToken");
                this.resumptionToken.write(context);
                context.getWriter().writeEndElement();
            }
        } catch (XMLStreamException e) {
            throw new WritingXmlException(e);
        }
    }

}
