//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.dataprovider.xml.oaipmh;

import com.lyncode.xoai.dataprovider.exceptions.WritingXmlException;
import com.lyncode.xoai.dataprovider.xml.XMLWritable;
import com.lyncode.xoai.dataprovider.xml.XmlOutputContext;

import javax.xml.bind.annotation.*;
import javax.xml.stream.XMLStreamException;
import java.util.Date;

import static com.lyncode.xoai.dataprovider.core.Granularity.Second;

/**
 * A resumptionToken may have 3 optional attributes and can be used in ListSets,
 * ListIdentifiers, ListRecords responses.
 *
 *
 * Java class for resumptionTokenType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 *











 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resumptionTokenType", propOrder = {"value"})
public class ResumptionTokenType implements XMLWritable {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "expirationDate")
    @XmlSchemaType(name = "dateTime")
    protected Date expirationDate;
    @XmlAttribute(name = "completeListSize")
    @XmlSchemaType(name = "positiveInteger")
    protected Long completeListSize;
    @XmlAttribute(name = "cursor")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Long cursor;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is ;
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is ;
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the expirationDate property.
     *
     * @return possible object is
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     *
     * @param value allowed object is
     */
    public void setExpirationDate(Date value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the completeListSize property.
     *
     * @return possible object is ;
     */
    public Long getCompleteListSize() {
        return completeListSize;
    }

    /**
     * Sets the value of the completeListSize property.
     *
     * @param value allowed object is ;
     */
    public void setCompleteListSize(Number value) {
        this.completeListSize = value.longValue();
    }

    /**
     * Gets the value of the cursor property.
     *
     * @return possible object is ;
     */
    public Long getCursor() {
        return cursor;
    }

    /**
     * Sets the value of the cursor property.
     *
     * @param value allowed object is ;
     */
    public void setCursor(Number value) {
        this.cursor = value.longValue();
    }

    /*
     *



     */
    @Override
    public void write(XmlOutputContext context) throws WritingXmlException {
        try {
            if (this.expirationDate != null)
                context.getWriter().writeAttribute("expirationDate", context.format(this.expirationDate, Second));
            if (this.completeListSize != null)
                context.getWriter().writeAttribute("completeListSize", "" + this.completeListSize);
            if (this.cursor != null)
                context.getWriter().writeAttribute("cursor", "" + this.cursor);
            if (this.value != null)
                context.getWriter().writeCharacters(this.value);
        } catch (XMLStreamException e) {
            throw new WritingXmlException(e);
        }
    }

}
