//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.dataprovider.xml.oaipmh;

import com.lyncode.xoai.dataprovider.exceptions.WritingXmlException;
import com.lyncode.xoai.dataprovider.xml.XMLWritable;
import com.lyncode.xoai.dataprovider.xml.XmlOutputContext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.stream.XMLStreamException;
import java.util.ArrayList;
import java.util.List;

import static com.lyncode.xoai.util.XmlIOUtils.writeElement;
import static com.lyncode.xoai.util.XmlIOUtils.writeValue;

/**
 *
 * Java class for setType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 *













 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setType", propOrder = {"setSpec", "setName", "setDescription"})
public class SetType implements XMLWritable {

    @XmlElement(required = true)
    protected String setSpec;
    @XmlElement(required = true)
    protected String setName;
    protected List<DescriptionType> setDescription;

    /**
     * Gets the value of the withSpec property.
     *
     * @return possible object is ;
     */
    public String getSetSpec() {
        return setSpec;
    }

    /**
     * Sets the value of the withSpec property.
     *
     * @param value allowed object is ;
     */
    public void setSetSpec(String value) {
        this.setSpec = value;
    }

    /**
     * Gets the value of the setName property.
     *
     * @return possible object is ;
     */
    public String getSetName() {
        return setName;
    }

    /**
     * Sets the value of the setName property.
     *
     * @param value allowed object is ;
     */
    public void setSetName(String value) {
        this.setName = value;
    }

    /**
     * Gets the value of the setDescription property.
     *
     *
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
      method for the setDescription property.
     *
     *
     * For example, to add a new item, do as follows:
     *

     * getSetDescription().add(newItem);

     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * ;
     */
    public List<DescriptionType> getSetDescription() {
        if (setDescription == null) {
            setDescription = new ArrayList<DescriptionType>();
        }
        return this.setDescription;
    }

	/*
     *



	 */

    @Override
    public void write(XmlOutputContext context) throws WritingXmlException {
        try {
            writeValue(context.getWriter(), "setSpec", setSpec);
            writeValue(context.getWriter(), "setName", setName);
            if (this.setDescription != null && !this.setDescription.isEmpty()) {
                for (DescriptionType desc : this.setDescription)
                    writeElement(context, "setDescription", desc);
            }
        } catch (XMLStreamException e) {
            throw new WritingXmlException(e);
        }
    }

}
