//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 11:34:41 PM BST 
//


package com.lyncode.xoai.dataprovider.xml.xoaiconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BundleReference complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="BundleReference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="refid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BundleReference")
public class BundleReference {

    @XmlAttribute(name = "refid")
    protected String refid;

    /**
     * Gets the value of the refid property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRefid() {
        return refid;
    }

    /**
     * Sets the value of the refid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRefid(String value) {
        this.refid = value;
    }

}
