//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 11:34:41 PM BST 
//


package com.lyncode.xoai.dataprovider.xml.xoaiconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConditionDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConditionDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="And">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LeftCondition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
 *                   &lt;element name="RightCondition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Or">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LeftCondition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
 *                   &lt;element name="RightCondition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Not">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Condition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Custom" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionDefinitionType", propOrder = {
    "and",
    "or",
    "not",
    "custom"
})
public class ConditionDefinitionType {

    @XmlElement(name = "And")
    protected ConditionDefinitionType.And and;
    @XmlElement(name = "Or")
    protected ConditionDefinitionType.Or or;
    @XmlElement(name = "Not")
    protected ConditionDefinitionType.Not not;
    @XmlElement(name = "Custom")
    protected BundleReference custom;

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionDefinitionType.And }
     *     
     */
    public ConditionDefinitionType.And getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionDefinitionType.And }
     *     
     */
    public void setAnd(ConditionDefinitionType.And value) {
        this.and = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionDefinitionType.Or }
     *     
     */
    public ConditionDefinitionType.Or getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionDefinitionType.Or }
     *     
     */
    public void setOr(ConditionDefinitionType.Or value) {
        this.or = value;
    }

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionDefinitionType.Not }
     *     
     */
    public ConditionDefinitionType.Not getNot() {
        return not;
    }

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionDefinitionType.Not }
     *     
     */
    public void setNot(ConditionDefinitionType.Not value) {
        this.not = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link BundleReference }
     *     
     */
    public BundleReference getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleReference }
     *     
     */
    public void setCustom(BundleReference value) {
        this.custom = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LeftCondition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
     *         &lt;element name="RightCondition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "leftCondition",
        "rightCondition"
    })
    public static class And {

        @XmlElement(name = "LeftCondition", required = true)
        protected ConditionDefinitionType leftCondition;
        @XmlElement(name = "RightCondition", required = true)
        protected ConditionDefinitionType rightCondition;

        /**
         * Gets the value of the leftCondition property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public ConditionDefinitionType getLeftCondition() {
            return leftCondition;
        }

        /**
         * Sets the value of the leftCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public void setLeftCondition(ConditionDefinitionType value) {
            this.leftCondition = value;
        }

        /**
         * Gets the value of the rightCondition property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public ConditionDefinitionType getRightCondition() {
            return rightCondition;
        }

        /**
         * Sets the value of the rightCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public void setRightCondition(ConditionDefinitionType value) {
            this.rightCondition = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Condition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "condition"
    })
    public static class Not {

        @XmlElement(name = "Condition", required = true)
        protected ConditionDefinitionType condition;

        /**
         * Gets the value of the condition property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public ConditionDefinitionType getCondition() {
            return condition;
        }

        /**
         * Sets the value of the condition property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public void setCondition(ConditionDefinitionType value) {
            this.condition = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LeftCondition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
     *         &lt;element name="RightCondition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "leftCondition",
        "rightCondition"
    })
    public static class Or {

        @XmlElement(name = "LeftCondition", required = true)
        protected ConditionDefinitionType leftCondition;
        @XmlElement(name = "RightCondition", required = true)
        protected ConditionDefinitionType rightCondition;

        /**
         * Gets the value of the leftCondition property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public ConditionDefinitionType getLeftCondition() {
            return leftCondition;
        }

        /**
         * Sets the value of the leftCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public void setLeftCondition(ConditionDefinitionType value) {
            this.leftCondition = value;
        }

        /**
         * Gets the value of the rightCondition property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public ConditionDefinitionType getRightCondition() {
            return rightCondition;
        }

        /**
         * Sets the value of the rightCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionDefinitionType }
         *     
         */
        public void setRightCondition(ConditionDefinitionType value) {
            this.rightCondition = value;
        }

    }

}
