//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 02:44:08 AM WEST 
//


package com.lyncode.xoai.dataprovider.xml.xoaiconfig;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Contexts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Context" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Transformer" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" minOccurs="0"/>
 *                             &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Set" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Format" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="baseurl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Formats">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Format" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SchemaLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Transformers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Transformer" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Filters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Filter" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sets" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Set" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="maxListRecordsSize" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *       &lt;attribute name="maxListSetsSize" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *       &lt;attribute name="maxListIdentifiersSize" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *       &lt;attribute name="identation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="stylesheet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contexts",
    "formats",
    "transformers",
    "filters",
    "sets"
})
@XmlRootElement(name = "Configuration")
public class Configuration {

    @XmlElement(name = "Contexts", required = true)
    protected Configuration.Contexts contexts;
    @XmlElement(name = "Formats", required = true)
    protected Configuration.Formats formats;
    @XmlElement(name = "Transformers")
    protected Configuration.Transformers transformers;
    @XmlElement(name = "Filters")
    protected Configuration.Filters filters;
    @XmlElement(name = "Sets")
    protected Configuration.Sets sets;
    @XmlAttribute
    protected Integer maxListRecordsSize;
    @XmlAttribute
    protected Integer maxListSetsSize;
    @XmlAttribute
    protected Integer maxListIdentifiersSize;
    @XmlAttribute
    protected Boolean identation;
    @XmlAttribute
    protected String stylesheet;

    /**
     * Gets the value of the contexts property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Contexts }
     *     
     */
    public Configuration.Contexts getContexts() {
        return contexts;
    }

    /**
     * Sets the value of the contexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Contexts }
     *     
     */
    public void setContexts(Configuration.Contexts value) {
        this.contexts = value;
    }

    /**
     * Gets the value of the formats property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Formats }
     *     
     */
    public Configuration.Formats getFormats() {
        return formats;
    }

    /**
     * Sets the value of the formats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Formats }
     *     
     */
    public void setFormats(Configuration.Formats value) {
        this.formats = value;
    }

    /**
     * Gets the value of the transformers property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Transformers }
     *     
     */
    public Configuration.Transformers getTransformers() {
        return transformers;
    }

    /**
     * Sets the value of the transformers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Transformers }
     *     
     */
    public void setTransformers(Configuration.Transformers value) {
        this.transformers = value;
    }

    /**
     * Gets the value of the filters property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Filters }
     *     
     */
    public Configuration.Filters getFilters() {
        return filters;
    }

    /**
     * Sets the value of the filters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Filters }
     *     
     */
    public void setFilters(Configuration.Filters value) {
        this.filters = value;
    }

    /**
     * Gets the value of the sets property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Sets }
     *     
     */
    public Configuration.Sets getSets() {
        return sets;
    }

    /**
     * Sets the value of the sets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Sets }
     *     
     */
    public void setSets(Configuration.Sets value) {
        this.sets = value;
    }

    /**
     * Gets the value of the maxListRecordsSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxListRecordsSize() {
        if (maxListRecordsSize == null) {
            return  100;
        } else {
            return maxListRecordsSize;
        }
    }

    /**
     * Sets the value of the maxListRecordsSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxListRecordsSize(Integer value) {
        this.maxListRecordsSize = value;
    }

    /**
     * Gets the value of the maxListSetsSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxListSetsSize() {
        if (maxListSetsSize == null) {
            return  100;
        } else {
            return maxListSetsSize;
        }
    }

    /**
     * Sets the value of the maxListSetsSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxListSetsSize(Integer value) {
        this.maxListSetsSize = value;
    }

    /**
     * Gets the value of the maxListIdentifiersSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxListIdentifiersSize() {
        if (maxListIdentifiersSize == null) {
            return  100;
        } else {
            return maxListIdentifiersSize;
        }
    }

    /**
     * Sets the value of the maxListIdentifiersSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxListIdentifiersSize(Integer value) {
        this.maxListIdentifiersSize = value;
    }

    /**
     * Gets the value of the identation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIdentation() {
        if (identation == null) {
            return false;
        } else {
            return identation;
        }
    }

    /**
     * Sets the value of the identation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIdentation(Boolean value) {
        this.identation = value;
    }

    /**
     * Gets the value of the stylesheet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStylesheet() {
        return stylesheet;
    }

    /**
     * Sets the value of the stylesheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStylesheet(String value) {
        this.stylesheet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Context" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Transformer" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" minOccurs="0"/>
     *                   &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Set" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Format" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="baseurl" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "context"
    })
    public static class Contexts {

        @XmlElement(name = "Context", required = true)
        protected List<Configuration.Contexts.Context> context;

        /**
         * Gets the value of the context property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the context property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContext().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Contexts.Context }
         * 
         * 
         */
        public List<Configuration.Contexts.Context> getContext() {
            if (context == null) {
                context = new ArrayList<Configuration.Contexts.Context>();
            }
            return this.context;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Transformer" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" minOccurs="0"/>
         *         &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Set" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Format" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="baseurl" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "transformer",
            "filter",
            "set",
            "format"
        })
        public static class Context {

            @XmlElement(name = "Transformer")
            protected BundleReference transformer;
            @XmlElement(name = "Filter")
            protected List<BundleReference> filter;
            @XmlElement(name = "Set")
            protected List<BundleReference> set;
            @XmlElement(name = "Format", required = true)
            protected List<BundleReference> format;
            @XmlAttribute
            protected String baseurl;

            /**
             * Gets the value of the transformer property.
             * 
             * @return
             *     possible object is
             *     {@link BundleReference }
             *     
             */
            public BundleReference getTransformer() {
                return transformer;
            }

            /**
             * Sets the value of the transformer property.
             * 
             * @param value
             *     allowed object is
             *     {@link BundleReference }
             *     
             */
            public void setTransformer(BundleReference value) {
                this.transformer = value;
            }

            /**
             * Gets the value of the filter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the filter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFilter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             * 
             * 
             */
            public List<BundleReference> getFilter() {
                if (filter == null) {
                    filter = new ArrayList<BundleReference>();
                }
                return this.filter;
            }

            /**
             * Gets the value of the set property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the set property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSet().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             * 
             * 
             */
            public List<BundleReference> getSet() {
                if (set == null) {
                    set = new ArrayList<BundleReference>();
                }
                return this.set;
            }

            /**
             * Gets the value of the format property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the format property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFormat().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             * 
             * 
             */
            public List<BundleReference> getFormat() {
                if (format == null) {
                    format = new ArrayList<BundleReference>();
                }
                return this.format;
            }

            /**
             * Gets the value of the baseurl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseurl() {
                return baseurl;
            }

            /**
             * Sets the value of the baseurl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseurl(String value) {
                this.baseurl = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Filter" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class Filters {

        @XmlElement(name = "Filter", required = true)
        protected List<Configuration.Filters.Filter> filter;

        /**
         * Gets the value of the filter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the filter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFilter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Filters.Filter }
         * 
         * 
         */
        public List<Configuration.Filters.Filter> getFilter() {
            if (filter == null) {
                filter = new ArrayList<Configuration.Filters.Filter>();
            }
            return this.filter;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clazz",
            "parameter"
        })
        public static class Filter {

            @XmlElement(name = "Class", required = true)
            protected String clazz;
            @XmlElement(name = "Parameter")
            protected List<Parameter> parameter;
            @XmlAttribute
            protected String id;

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the parameter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the parameter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParameter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parameter }
             * 
             * 
             */
            public List<Parameter> getParameter() {
                if (parameter == null) {
                    parameter = new ArrayList<Parameter>();
                }
                return this.parameter;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Format" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SchemaLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "format"
    })
    public static class Formats {

        @XmlElement(name = "Format", required = true)
        protected List<Configuration.Formats.Format> format;

        /**
         * Gets the value of the format property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the format property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFormat().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Formats.Format }
         * 
         * 
         */
        public List<Configuration.Formats.Format> getFormat() {
            if (format == null) {
                format = new ArrayList<Configuration.Formats.Format>();
            }
            return this.format;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SchemaLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "prefix",
            "xslt",
            "namespace",
            "schemaLocation",
            "filter"
        })
        public static class Format {

            @XmlElement(name = "Prefix", required = true)
            protected String prefix;
            @XmlElement(name = "XSLT", required = true)
            protected String xslt;
            @XmlElement(name = "Namespace", required = true)
            protected String namespace;
            @XmlElement(name = "SchemaLocation", required = true)
            protected String schemaLocation;
            @XmlElement(name = "Filter")
            protected List<BundleReference> filter;
            @XmlAttribute
            protected String id;

            /**
             * Gets the value of the prefix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrefix() {
                return prefix;
            }

            /**
             * Sets the value of the prefix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrefix(String value) {
                this.prefix = value;
            }

            /**
             * Gets the value of the xslt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXSLT() {
                return xslt;
            }

            /**
             * Sets the value of the xslt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXSLT(String value) {
                this.xslt = value;
            }

            /**
             * Gets the value of the namespace property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNamespace() {
                return namespace;
            }

            /**
             * Sets the value of the namespace property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNamespace(String value) {
                this.namespace = value;
            }

            /**
             * Gets the value of the schemaLocation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSchemaLocation() {
                return schemaLocation;
            }

            /**
             * Sets the value of the schemaLocation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSchemaLocation(String value) {
                this.schemaLocation = value;
            }

            /**
             * Gets the value of the filter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the filter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFilter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             * 
             * 
             */
            public List<BundleReference> getFilter() {
                if (filter == null) {
                    filter = new ArrayList<BundleReference>();
                }
                return this.filter;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Set" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "set"
    })
    public static class Sets {

        @XmlElement(name = "Set", required = true)
        protected List<Configuration.Sets.Set> set;

        /**
         * Gets the value of the set property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the set property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Sets.Set }
         * 
         * 
         */
        public List<Configuration.Sets.Set> getSet() {
            if (set == null) {
                set = new ArrayList<Configuration.Sets.Set>();
            }
            return this.set;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Filter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pattern",
            "name",
            "filter",
            "parameter"
        })
        public static class Set {

            @XmlElement(name = "Pattern", required = true)
            protected String pattern;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Filter")
            protected List<BundleReference> filter;
            @XmlElement(name = "Parameter")
            protected List<Parameter> parameter;
            @XmlAttribute
            protected String id;

            /**
             * Gets the value of the pattern property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPattern() {
                return pattern;
            }

            /**
             * Sets the value of the pattern property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPattern(String value) {
                this.pattern = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the filter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the filter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFilter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             * 
             * 
             */
            public List<BundleReference> getFilter() {
                if (filter == null) {
                    filter = new ArrayList<BundleReference>();
                }
                return this.filter;
            }

            /**
             * Gets the value of the parameter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the parameter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParameter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parameter }
             * 
             * 
             */
            public List<Parameter> getParameter() {
                if (parameter == null) {
                    parameter = new ArrayList<Parameter>();
                }
                return this.parameter;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Transformer" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transformer"
    })
    public static class Transformers {

        @XmlElement(name = "Transformer", required = true)
        protected List<Configuration.Transformers.Transformer> transformer;

        /**
         * Gets the value of the transformer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transformer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransformer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Transformers.Transformer }
         * 
         * 
         */
        public List<Configuration.Transformers.Transformer> getTransformer() {
            if (transformer == null) {
                transformer = new ArrayList<Configuration.Transformers.Transformer>();
            }
            return this.transformer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "xslt"
        })
        public static class Transformer {

            @XmlElement(name = "XSLT", required = true)
            protected String xslt;
            @XmlAttribute
            protected String id;

            /**
             * Gets the value of the xslt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXSLT() {
                return xslt;
            }

            /**
             * Sets the value of the xslt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXSLT(String value) {
                this.xslt = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
