//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 11:34:41 PM BST 
//


package com.lyncode.xoai.dataprovider.xml.xoaiconfig;

import com.lyncode.xoai.dataprovider.exceptions.ConfigurationException;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.*;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "contexts",
        "formats",
        "transformers",
        "filters",
        "sets"
})
@XmlRootElement(name = "Configuration")
public class Configuration {
    public static Configuration readConfiguration(InputStream input) throws ConfigurationException {
        try {
            JAXBContext context = JAXBContext.newInstance(Configuration.class
                    .getPackage().getName());
            Unmarshaller marshaller = context.createUnmarshaller();
            Object obj = marshaller.unmarshal(input);
            input.close();
            if (obj instanceof Configuration) {
                return (Configuration) obj;
            } else
                throw new ConfigurationException("Invalid configuration bundle");
        } catch (IOException ex) {
            throw new ConfigurationException(ex.getMessage(), ex);
        } catch (JAXBException ex) {
            throw new ConfigurationException(ex.getMessage(), ex);
        }
    }


    @XmlElement(name = "Contexts", required = true)
    protected Configuration.Contexts contexts;
    @XmlElement(name = "Formats", required = true)
    protected Configuration.Formats formats;
    @XmlElement(name = "Transformers")
    protected Configuration.Transformers transformers;
    @XmlElement(name = "Filters")
    protected Configuration.Filters filters;
    @XmlElement(name = "Sets")
    protected Configuration.Sets sets;
    @XmlAttribute(name = "maxListRecordsSize")
    protected Integer maxListRecordsSize;
    @XmlAttribute(name = "maxListSetsSize")
    protected Integer maxListSetsSize;
    @XmlAttribute(name = "maxListIdentifiersSize")
    protected Integer maxListIdentifiersSize;
    @XmlAttribute(name = "indentation")
    protected Boolean indentation;
    @XmlAttribute(name = "stylesheet")
    protected String stylesheet;
    @XmlAttribute(name = "descriptionFile")
    protected String descriptionFile;

    public void write(OutputStream output) throws ConfigurationException {
        try {
            JAXBContext context = JAXBContext.newInstance(Configuration.class
                    .getPackage().getName());
            Marshaller marshaller = context.createMarshaller();
            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
            marshaller.marshal(this, output);
            output.close();
        } catch (IOException ex) {
            throw new ConfigurationException(ex.getMessage(), ex);
        } catch (JAXBException ex) {
            throw new ConfigurationException(ex.getMessage(), ex);
        }
    }

    /**
     * Gets the value of the contexts property.
     *
     * @return possible object is
     *         {@link Configuration.Contexts }
     */
    public Configuration.Contexts getContexts() {
        return contexts;
    }

    /**
     * Sets the value of the contexts property.
     *
     * @param value allowed object is
     *              {@link Configuration.Contexts }
     */
    public void setContexts(Configuration.Contexts value) {
        this.contexts = value;
    }

    /**
     * Gets the value of the formats property.
     *
     * @return possible object is
     *         {@link Configuration.Formats }
     */
    public Configuration.Formats getFormats() {
        return formats;
    }

    /**
     * Sets the value of the formats property.
     *
     * @param value allowed object is
     *              {@link Configuration.Formats }
     */
    public void setFormats(Configuration.Formats value) {
        this.formats = value;
    }

    /**
     * Gets the value of the transformers property.
     *
     * @return possible object is
     *         {@link Configuration.Transformers }
     */
    public Configuration.Transformers getTransformers() {
        return transformers;
    }

    /**
     * Sets the value of the transformers property.
     *
     * @param value allowed object is
     *              {@link Configuration.Transformers }
     */
    public void setTransformers(Configuration.Transformers value) {
        this.transformers = value;
    }

    /**
     * Gets the value of the filters property.
     *
     * @return possible object is
     *         {@link Configuration.Filters }
     */
    public Configuration.Filters getFilters() {
        return filters;
    }

    /**
     * Sets the value of the filters property.
     *
     * @param value allowed object is
     *              {@link Configuration.Filters }
     */
    public void setFilters(Configuration.Filters value) {
        this.filters = value;
    }

    /**
     * Gets the value of the sets property.
     *
     * @return possible object is
     *         {@link Configuration.Sets }
     */
    public Configuration.Sets getSets() {
        return sets;
    }

    /**
     * Sets the value of the sets property.
     *
     * @param value allowed object is
     *              {@link Configuration.Sets }
     */
    public void setSets(Configuration.Sets value) {
        this.sets = value;
    }

    /**
     * Gets the value of the maxListRecordsSize property.
     *
     * @return possible object is
     *         {@link Integer }
     */
    public int getMaxListRecordsSize() {
        if (maxListRecordsSize == null) {
            return 100;
        } else {
            return maxListRecordsSize;
        }
    }

    /**
     * Sets the value of the maxListRecordsSize property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMaxListRecordsSize(Integer value) {
        this.maxListRecordsSize = value;
    }

    /**
     * Gets the value of the maxListSetsSize property.
     *
     * @return possible object is
     *         {@link Integer }
     */
    public int getMaxListSetsSize() {
        if (maxListSetsSize == null) {
            return 100;
        } else {
            return maxListSetsSize;
        }
    }

    /**
     * Sets the value of the maxListSetsSize property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMaxListSetsSize(Integer value) {
        this.maxListSetsSize = value;
    }

    /**
     * Gets the value of the maxListIdentifiersSize property.
     *
     * @return possible object is
     *         {@link Integer }
     */
    public int getMaxListIdentifiersSize() {
        if (maxListIdentifiersSize == null) {
            return 100;
        } else {
            return maxListIdentifiersSize;
        }
    }

    /**
     * Sets the value of the maxListIdentifiersSize property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMaxListIdentifiersSize(Integer value) {
        this.maxListIdentifiersSize = value;
    }

    /**
     * Gets the value of the indentation property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isIndentation() {
        if (indentation == null) {
            return false;
        } else {
            return indentation;
        }
    }

    /**
     * Sets the value of the indentation property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIndentation(Boolean value) {
        this.indentation = value;
    }

    /**
     * Gets the value of the stylesheet property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getStylesheet() {
        return stylesheet;
    }

    /**
     * Sets the value of the stylesheet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStylesheet(String value) {
        this.stylesheet = value;
    }

    /**
     * Gets the value of the descriptionFile property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDescriptionFile() {
        return descriptionFile;
    }

    /**
     * Sets the value of the descriptionFile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescriptionFile(String value) {
        this.descriptionFile = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Context" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Transformer" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" minOccurs="0"/>
     *                   &lt;element name="ScopedFilter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Set" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Format" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="baseurl" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "context"
    })
    public static class Contexts {

        @XmlElement(name = "Context", required = true)
        protected List<Configuration.Contexts.Context> context;

        /**
         * Gets the value of the context property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the context property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContext().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Contexts.Context }
         */
        public List<Configuration.Contexts.Context> getContext() {
            if (context == null) {
                context = new ArrayList<Configuration.Contexts.Context>();
            }
            return this.context;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Transformer" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" minOccurs="0"/>
         *         &lt;element name="ScopedFilter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Set" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Format" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="baseurl" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "transformer",
                "filter",
                "set",
                "format"
        })
        public static class Context {

            @XmlElement(name = "Transformer")
            protected BundleReference transformer;
            @XmlElement(name = "Filter")
            protected List<BundleReference> filter;
            @XmlElement(name = "Set")
            protected List<BundleReference> set;
            @XmlElement(name = "Format", required = true)
            protected List<BundleReference> format;
            @XmlAttribute(name = "baseurl")
            protected String baseurl;

            /**
             * Gets the value of the transformer property.
             *
             * @return possible object is
             *         {@link BundleReference }
             */
            public BundleReference getTransformer() {
                return transformer;
            }

            /**
             * Sets the value of the transformer property.
             *
             * @param value allowed object is
             *              {@link BundleReference }
             */
            public void setTransformer(BundleReference value) {
                this.transformer = value;
            }

            /**
             * Gets the value of the filter property.
             * <p/>
             * <p/>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the filter property.
             * <p/>
             * <p/>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFilter().add(newItem);
             * </pre>
             * <p/>
             * <p/>
             * <p/>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             */
            public List<BundleReference> getFilter() {
                if (filter == null) {
                    filter = new ArrayList<BundleReference>();
                }
                return this.filter;
            }

            /**
             * Gets the value of the set property.
             * <p/>
             * <p/>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the set property.
             * <p/>
             * <p/>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSet().add(newItem);
             * </pre>
             * <p/>
             * <p/>
             * <p/>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             */
            public List<BundleReference> getSet() {
                if (set == null) {
                    set = new ArrayList<BundleReference>();
                }
                return this.set;
            }

            /**
             * Gets the value of the format property.
             * <p/>
             * <p/>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the format property.
             * <p/>
             * <p/>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFormat().add(newItem);
             * </pre>
             * <p/>
             * <p/>
             * <p/>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             */
            public List<BundleReference> getFormat() {
                if (format == null) {
                    format = new ArrayList<BundleReference>();
                }
                return this.format;
            }

            /**
             * Gets the value of the baseurl property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getBaseurl() {
                return baseurl;
            }

            /**
             * Sets the value of the baseurl property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setBaseurl(String value) {
                this.baseurl = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CustomFilter" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Filter" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="definition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "customFilter",
            "filter"
    })
    public static class Filters {

        @XmlElement(name = "CustomFilter")
        protected List<Configuration.Filters.CustomFilter> customFilter;
        @XmlElement(name = "Filter")
        protected List<Configuration.Filters.Filter> filter;

        /**
         * Gets the value of the customFilter property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customFilter property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomFilter().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Filters.CustomFilter }
         */
        public List<Configuration.Filters.CustomFilter> getCustomFilter() {
            if (customFilter == null) {
                customFilter = new ArrayList<Configuration.Filters.CustomFilter>();
            }
            return this.customFilter;
        }

        /**
         * Gets the value of the filter property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the filter property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFilter().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Filters.Filter }
         */
        public List<Configuration.Filters.Filter> getFilter() {
            if (filter == null) {
                filter = new ArrayList<Configuration.Filters.Filter>();
            }
            return this.filter;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "clazz",
                "parameter"
        })
        public static class CustomFilter implements Referable {

            @XmlElement(name = "Class", required = true)
            protected String clazz;
            @XmlElement(name = "Parameter")
            protected List<Parameter> parameter;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the clazz property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the parameter property.
             * <p/>
             * <p/>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the parameter property.
             * <p/>
             * <p/>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParameter().add(newItem);
             * </pre>
             * <p/>
             * <p/>
             * <p/>
             * Objects of the following type(s) are allowed in the list
             * {@link Parameter }
             */
            public List<Parameter> getParameter() {
                if (parameter == null) {
                    parameter = new ArrayList<Parameter>();
                }
                return this.parameter;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setId(String value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="definition" type="{http://www.lyncode.com/XOAIConfiguration}ConditionDefinitionType" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "definition"
        })
        public static class Filter implements Referable {

            protected ConditionDefinitionType definition;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the definition property.
             *
             * @return possible object is
             *         {@link ConditionDefinitionType }
             */
            public ConditionDefinitionType getDefinition() {
                return definition;
            }

            /**
             * Sets the value of the definition property.
             *
             * @param value allowed object is
             *              {@link ConditionDefinitionType }
             */
            public void setDefinition(ConditionDefinitionType value) {
                this.definition = value;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Format" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SchemaLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ScopedFilter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "format"
    })
    public static class Formats {

        @XmlElement(name = "Format", required = true)
        protected List<Configuration.Formats.Format> format;

        /**
         * Gets the value of the format property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the format property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFormat().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Formats.Format }
         */
        public List<Configuration.Formats.Format> getFormat() {
            if (format == null) {
                format = new ArrayList<Configuration.Formats.Format>();
            }
            return this.format;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SchemaLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ScopedFilter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "prefix",
                "xslt",
                "namespace",
                "schemaLocation",
                "filter"
        })
        public static class Format implements Referable {

            @XmlElement(name = "Prefix", required = true)
            protected String prefix;
            @XmlElement(name = "XSLT", required = true)
            protected String xslt;
            @XmlElement(name = "Namespace", required = true)
            protected String namespace;
            @XmlElement(name = "SchemaLocation", required = true)
            protected String schemaLocation;
            @XmlElement(name = "ScopedFilter")
            protected List<BundleReference> filter;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the prefix property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getPrefix() {
                return prefix;
            }

            /**
             * Sets the value of the prefix property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPrefix(String value) {
                this.prefix = value;
            }

            /**
             * Gets the value of the xslt property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getXSLT() {
                return xslt;
            }

            /**
             * Sets the value of the xslt property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setXSLT(String value) {
                this.xslt = value;
            }

            /**
             * Gets the value of the namespace property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getNamespace() {
                return namespace;
            }

            /**
             * Sets the value of the namespace property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setNamespace(String value) {
                this.namespace = value;
            }

            /**
             * Gets the value of the schemaLocation property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getSchemaLocation() {
                return schemaLocation;
            }

            /**
             * Sets the value of the schemaLocation property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setSchemaLocation(String value) {
                this.schemaLocation = value;
            }

            /**
             * Gets the value of the filter property.
             * <p/>
             * <p/>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the filter property.
             * <p/>
             * <p/>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFilter().add(newItem);
             * </pre>
             * <p/>
             * <p/>
             * <p/>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             */
            public List<BundleReference> getFilter() {
                if (filter == null) {
                    filter = new ArrayList<BundleReference>();
                }
                return this.filter;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Set" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ScopedFilter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "set"
    })
    public static class Sets {

        @XmlElement(name = "Set", required = true)
        protected List<Configuration.Sets.Set> set;

        /**
         * Gets the value of the set property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the set property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSet().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Sets.Set }
         */
        public List<Configuration.Sets.Set> getSet() {
            if (set == null) {
                set = new ArrayList<Configuration.Sets.Set>();
            }
            return this.set;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ScopedFilter" type="{http://www.lyncode.com/XOAIConfiguration}BundleReference" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Parameter" type="{http://www.lyncode.com/XOAIConfiguration}Parameter" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "pattern",
                "name",
                "filter",
                "parameter"
        })
        public static class Set implements Referable {

            @XmlElement(name = "Pattern", required = true)
            protected String pattern;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "ScopedFilter")
            protected List<BundleReference> filter;
            @XmlElement(name = "Parameter")
            protected List<Parameter> parameter;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the pattern property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getPattern() {
                return pattern;
            }

            /**
             * Sets the value of the pattern property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPattern(String value) {
                this.pattern = value;
            }

            /**
             * Gets the value of the name property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the filter property.
             * <p/>
             * <p/>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the filter property.
             * <p/>
             * <p/>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFilter().add(newItem);
             * </pre>
             * <p/>
             * <p/>
             * <p/>
             * Objects of the following type(s) are allowed in the list
             * {@link BundleReference }
             */
            public List<BundleReference> getFilter() {
                if (filter == null) {
                    filter = new ArrayList<BundleReference>();
                }
                return this.filter;
            }

            /**
             * Gets the value of the parameter property.
             * <p/>
             * <p/>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the parameter property.
             * <p/>
             * <p/>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParameter().add(newItem);
             * </pre>
             * <p/>
             * <p/>
             * <p/>
             * Objects of the following type(s) are allowed in the list
             * {@link Parameter }
             */
            public List<Parameter> getParameter() {
                if (parameter == null) {
                    parameter = new ArrayList<Parameter>();
                }
                return this.parameter;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Transformer" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "transformer"
    })
    public static class Transformers {

        @XmlElement(name = "Transformer", required = true)
        protected List<Configuration.Transformers.Transformer> transformer;

        /**
         * Gets the value of the transformer property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transformer property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransformer().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Transformers.Transformer }
         */
        public List<Configuration.Transformers.Transformer> getTransformer() {
            if (transformer == null) {
                transformer = new ArrayList<Configuration.Transformers.Transformer>();
            }
            return this.transformer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="XSLT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "xslt"
        })
        public static class Transformer implements Referable {

            @XmlElement(name = "XSLT", required = true)
            protected String xslt;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the xslt property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getXSLT() {
                return xslt;
            }

            /**
             * Sets the value of the xslt property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setXSLT(String value) {
                this.xslt = value;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
