package com.lyncode.xoai.serviceprovider.oaipmh;

import static org.junit.Assert.*;

import java.io.ByteArrayInputStream;

import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamException;

import org.codehaus.stax2.XMLInputFactory2;
import org.junit.Test;
import org.mockito.Mockito;

import com.lyncode.xoai.serviceprovider.OAIServiceConfiguration;
import com.lyncode.xoai.serviceprovider.exceptions.ParseException;
import com.lyncode.xoai.serviceprovider.oaipmh.spec.ListIdentifiersType;
import com.lyncode.xoai.serviceprovider.oaipmh.spec.MetadataFormatType;
import com.lyncode.xoai.serviceprovider.parser.AboutItemParser;
import com.lyncode.xoai.serviceprovider.parser.AboutSetParser;
import com.lyncode.xoai.serviceprovider.parser.DescriptionParser;
import com.lyncode.xoai.serviceprovider.parser.MetadataParser;


public class ListIdentifiersParserTest {
    static String XML = "<ListIdentifiers>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/4</identifier>\r\n" + 
    		"            <datestamp>2013-09-10T20:40:03Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/3</identifier>\r\n" + 
    		"            <datestamp>2013-09-08T00:01:15Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/6</identifier>\r\n" + 
    		"            <datestamp>2013-09-08T02:00:36Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/5</identifier>\r\n" + 
    		"            <datestamp>2013-09-10T12:01:23Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/7</identifier>\r\n" + 
    		"            <datestamp>2013-09-08T02:00:42Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/8</identifier>\r\n" + 
    		"            <datestamp>2013-05-02T14:28:36Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/9</identifier>\r\n" + 
    		"            <datestamp>2013-07-15T11:26:04Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_8</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/10</identifier>\r\n" + 
    		"            <datestamp>2013-07-26T02:00:20Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/11</identifier>\r\n" + 
    		"            <datestamp>2013-08-25T02:12:53Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_10</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/12</identifier>\r\n" + 
    		"            <datestamp>2013-08-25T02:12:54Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_10</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/15</identifier>\r\n" + 
    		"            <datestamp>2013-09-04T02:00:21Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/13</identifier>\r\n" + 
    		"            <datestamp>2013-08-25T02:12:54Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_10</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/16</identifier>\r\n" + 
    		"            <datestamp>2013-09-04T02:00:22Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:1842/1759</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:38Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10459.3/13</identifier>\r\n" + 
    		"            <datestamp>2013-07-29T11:24:59Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_10</setSpec>\r\n" + 
    		"            <setSpec>col_10673_13</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/14</identifier>\r\n" + 
    		"            <datestamp>2013-08-26T16:04:32Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_10</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/17</identifier>\r\n" + 
    		"            <datestamp>2013-09-04T02:00:18Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/8</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:40Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/18</identifier>\r\n" + 
    		"            <datestamp>2013-09-05T02:00:35Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/9</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:41Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/10</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:42Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/20</identifier>\r\n" + 
    		"            <datestamp>2013-09-05T02:00:27Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2226</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:54:49Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/16</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:45Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/21</identifier>\r\n" + 
    		"            <datestamp>2013-09-05T02:00:33Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2228</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:54:55Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/17</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:46Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/19</identifier>\r\n" + 
    		"            <datestamp>2013-08-25T02:12:57Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_10</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/22</identifier>\r\n" + 
    		"            <datestamp>2013-09-05T02:00:37Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2229</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:54:59Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/19</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:47Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/23</identifier>\r\n" + 
    		"            <datestamp>2013-09-05T02:00:38Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2230</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:04Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/24</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:48Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/66</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:18Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10459.3/52</identifier>\r\n" + 
    		"            <datestamp>2013-07-29T11:25:04Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_10</setSpec>\r\n" + 
    		"            <setSpec>col_10673_13</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2231</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:08Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/25</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:49Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/62</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:19Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10459.3/53</identifier>\r\n" + 
    		"            <datestamp>2013-07-29T11:25:05Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_10</setSpec>\r\n" + 
    		"            <setSpec>col_10673_13</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2232</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:14Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/45</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:51Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/63</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:19Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/25</identifier>\r\n" + 
    		"            <datestamp>2013-09-05T13:53:51Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/24</identifier>\r\n" + 
    		"            <datestamp>2013-09-11T02:00:54Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2233</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:16Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/46</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:52Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/64</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:20Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/26</identifier>\r\n" + 
    		"            <datestamp>2013-09-06T02:00:28Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2234</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:20Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/47</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:53Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/68</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:20Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2235</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:21Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/130</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:53Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/70</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:21Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/27</identifier>\r\n" + 
    		"            <datestamp>2013-09-07T02:00:31Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2236</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:24Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/131</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:54Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/74</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:21Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/28</identifier>\r\n" + 
    		"            <datestamp>2013-09-07T02:00:37Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2237</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:27Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/132</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:55Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/65</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:22Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2238</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:28Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/128</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:55Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/67</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:22Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10459.3/60</identifier>\r\n" + 
    		"            <datestamp>2013-07-29T11:25:08Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_10</setSpec>\r\n" + 
    		"            <setSpec>col_10673_13</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2240</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:31Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/123</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:56Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/69</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:22Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10459.3/61</identifier>\r\n" + 
    		"            <datestamp>2013-07-29T11:25:08Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_10</setSpec>\r\n" + 
    		"            <setSpec>col_10673_13</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/30</identifier>\r\n" + 
    		"            <datestamp>2013-08-25T02:13:03Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_10</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/32</identifier>\r\n" + 
    		"            <datestamp>2013-09-07T02:00:39Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/29</identifier>\r\n" + 
    		"            <datestamp>2013-09-10T12:53:52Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2241</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:32Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/141</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:58Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/73</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:23Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/31</identifier>\r\n" + 
    		"            <datestamp>2013-08-25T02:13:03Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_10</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/33</identifier>\r\n" + 
    		"            <datestamp>2013-09-07T02:00:39Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/34</identifier>\r\n" + 
    		"            <datestamp>2013-09-11T02:00:49Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_32</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2242</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:34Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/144</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:59Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/72</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:24Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/36</identifier>\r\n" + 
    		"            <datestamp>2013-09-07T02:00:36Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_34</setSpec>\r\n" + 
    		"            <setSpec>col_10673_35</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/35</identifier>\r\n" + 
    		"            <datestamp>2013-09-10T13:28:47Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_9</setSpec>\r\n" + 
    		"            <setSpec>col_10673_32</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2243</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:35Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/163</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:16:59Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/75</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:24Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/38</identifier>\r\n" + 
    		"            <datestamp>2013-09-11T02:00:31Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2244</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:37Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/182</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:17:00Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/76</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:24Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10673/39</identifier>\r\n" + 
    		"            <datestamp>2013-09-10T20:36:27Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_2</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2245</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:39Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/184</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:17:00Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/77</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:25Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10986/2246</identifier>\r\n" + 
    		"            <datestamp>2013-05-06T16:55:41Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_18</setSpec>\r\n" + 
    		"            <setSpec>col_10673_19</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10283/185</identifier>\r\n" + 
    		"            <datestamp>2013-06-17T07:17:01Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_1</setSpec>\r\n" + 
    		"            <setSpec>col_10673_11</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:2318/78</identifier>\r\n" + 
    		"            <datestamp>2013-07-09T22:59:26Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_16</setSpec>\r\n" + 
    		"            <setSpec>col_10673_21</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <header>\r\n" + 
    		"            <identifier>oai:demo.dspace.org:10459.3/67</identifier>\r\n" + 
    		"            <datestamp>2013-07-29T11:25:13Z</datestamp>\r\n" + 
    		"            <setSpec>com_10673_10</setSpec>\r\n" + 
    		"            <setSpec>col_10673_13</setSpec>\r\n" + 
    		"        </header>\r\n" + 
    		"        <resumptionToken completeListSize=\"16816\" cursor=\"0\">MToxMDB8Mjp8Mzp8NDp8NTpvYWlfZGM=</resumptionToken>\r\n" + 
    		"    </ListIdentifiers>";

    @Test
    public void testListIdentifiers() throws XMLStreamException, ParseException {
        XMLInputFactory factory = XMLInputFactory2.newFactory();
        XMLEventReader reader = factory.createXMLEventReader(new ByteArrayInputStream(XML.getBytes()));

        reader.nextEvent();
        reader.peek();
        
        OAIServiceConfiguration<MetadataParser, AboutItemParser, DescriptionParser, AboutSetParser> config = Mockito.mock(OAIServiceConfiguration.class);
        ListIdentifiersParser parser = new ListIdentifiersParser(config);
        
        //System.out.println(parser.parse(reader));
        ListIdentifiersType result = parser.parse(reader);
        

        assertEquals(100, result.getHeader().size());
        assertEquals("MToxMDB8Mjp8Mzp8NDp8NTpvYWlfZGM=", result.getResumptionToken().getValue());
    }

}
