//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.serviceprovider.oaipmh.spec;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * Java class for granularityType.
 * 
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * 








 * 
 */
@XmlType(name = "granularityType")
@XmlEnum
public enum GranularityType {

	@XmlEnumValue("YYYY-MM-DD")
	YYYY_MM_DD("YYYY-MM-DD"), @XmlEnumValue("YYYY-MM-DDThh:mm:ssZ")
	YYYY_MM_DD_THH_MM_SS_Z("YYYY-MM-DDThh:mm:ssZ");
	private final String value;

	GranularityType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static GranularityType fromValue(String v) {
		for (GranularityType c : GranularityType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
