//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.serviceprovider.oaipmh.spec;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * A header has a unique identifier, a datestamp, and setSpec(s) in case the
 * item from which the record is disseminated belongs to set(s). the header can
 * carry a deleted status indicating that the record is deleted.
 * 
 *
 * Java class for headerType complex type.
 * 
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 














 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "headerType", propOrder = { "identifier", "datestamp",
		"setSpec" })
public class HeaderType {

	@XmlElement(required = true)
	protected String identifier;
	@XmlElement(required = true)
	protected Date datestamp;
	protected List<String> setSpec;
	@XmlAttribute(name = "status")
	protected StatusType status;

	/**
	 * Gets the value of the identifier property.
	 * 
	 * @return possible object is ;
	 * 
	 */
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * Sets the value of the identifier property.
	 * 
	 * @param value
	 *            allowed object is ;
	 * 
	 */
	public void setIdentifier(String value) {
		this.identifier = value;
	}

	/**
	 * Gets the value of the datestamp property.
	 * 
	 * @return possible object is ;
	 * 
	 */
	public Date getDatestamp() {
		return datestamp;
	}

	/**
	 * Sets the value of the datestamp property.
	 * 
	 * @param value
	 *            allowed object is ;
	 * 
	 */
	public void setDatestamp(Date value) {
		this.datestamp = value;
	}

	/**
	 * Gets the value of the setSpec property.
	 * 
	 *
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	  method for the setSpec property.
	 * 
	 *
	 * For example, to add a new item, do as follows:
	 * 

	 * getSetSpec().add(newItem);

	 * 
	 * 
	 *
	 * Objects of the following type(s) are allowed in the list ;
	 * 
	 * 
	 */
	public List<String> getSetSpec() {
		if (setSpec == null) {
			setSpec = new ArrayList<String>();
		}
		return this.setSpec;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is ;
	 * 
	 */
	public StatusType getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is ;
	 * 
	 */
	public void setStatus(StatusType value) {
		this.status = value;
	}

}
