//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.serviceprovider.oaipmh.spec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * Metadata must be expressed in XML that complies with another XML Schema
 * (namespace=#other). Metadata must be explicitly qualified in the response.
 * 
 *
 * Java class for metadataType complex type.
 * 
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 











 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadataType")
public class MetadataType {

	@XmlValue
	protected Object value;

	/**
	 * Gets the value of the any property.
	 * 
	 * @return possible object is ;
	 * 
	 */
	public Object getAny() {
		return value;
	}

	/**
	 * Sets the value of the any property.
	 * 
	 * @param value
	 *            allowed object is ;
	 * 
	 */
	public void setAny(Object value) {
		this.value = value;
	}

}
