//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package com.lyncode.xoai.serviceprovider.oaipmh.spec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * Java class for setType complex type.
 * 
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 













 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setType", propOrder = { "setSpec", "setName", "setDescription" })
public class SetType {

	@XmlElement(required = true)
	protected String setSpec;
	@XmlElement(required = true)
	protected String setName;
	protected List<DescriptionType> setDescription;

	/**
	 * Gets the value of the setSpec property.
	 * 
	 * @return possible object is ;
	 * 
	 */
	public String getSetSpec() {
		return setSpec;
	}

	/**
	 * Sets the value of the setSpec property.
	 * 
	 * @param value
	 *            allowed object is ;
	 * 
	 */
	public void setSetSpec(String value) {
		this.setSpec = value;
	}

	/**
	 * Gets the value of the setName property.
	 * 
	 * @return possible object is ;
	 * 
	 */
	public String getSetName() {
		return setName;
	}

	/**
	 * Sets the value of the setName property.
	 * 
	 * @param value
	 *            allowed object is ;
	 * 
	 */
	public void setSetName(String value) {
		this.setName = value;
	}

	/**
	 * Gets the value of the setDescription property.
	 * 
	 *
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	  method for the setDescription property.
	 * 
	 *
	 * For example, to add a new item, do as follows:
	 * 

	 * getSetDescription().add(newItem);

	 * 
	 * 
	 *
	 * Objects of the following type(s) are allowed in the list
	 * ;
	 * 
	 * 
	 */
	public List<DescriptionType> getSetDescription() {
		if (setDescription == null) {
			setDescription = new ArrayList<DescriptionType>();
		}
		return this.setDescription;
	}

}
