//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.27 at 03:32:38 AM WEST 
//


package com.lyncode.xoai.common.dataprovider.xml.xoaiconfig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lyncode.xoai.common.dataprovider.xml.xoaiconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lyncode.xoai.common.dataprovider.xml.xoaiconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Configuration.Contexts.Context }
     * 
     */
    public Configuration.Contexts.Context createConfigurationContextsContext() {
        return new Configuration.Contexts.Context();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Configuration.Filters.Filter }
     * 
     */
    public Configuration.Filters.Filter createConfigurationFiltersFilter() {
        return new Configuration.Filters.Filter();
    }

    /**
     * Create an instance of {@link Configuration.Filters }
     * 
     */
    public Configuration.Filters createConfigurationFilters() {
        return new Configuration.Filters();
    }

    /**
     * Create an instance of {@link Configuration.Transformers.Transformer }
     * 
     */
    public Configuration.Transformers.Transformer createConfigurationTransformersTransformer() {
        return new Configuration.Transformers.Transformer();
    }

    /**
     * Create an instance of {@link Configuration.Contexts }
     * 
     */
    public Configuration.Contexts createConfigurationContexts() {
        return new Configuration.Contexts();
    }

    /**
     * Create an instance of {@link Configuration.Sets.Set }
     * 
     */
    public Configuration.Sets.Set createConfigurationSetsSet() {
        return new Configuration.Sets.Set();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Configuration.Formats.Format }
     * 
     */
    public Configuration.Formats.Format createConfigurationFormatsFormat() {
        return new Configuration.Formats.Format();
    }

    /**
     * Create an instance of {@link BundleReference }
     * 
     */
    public BundleReference createBundleReference() {
        return new BundleReference();
    }

    /**
     * Create an instance of {@link Configuration.Sets }
     * 
     */
    public Configuration.Sets createConfigurationSets() {
        return new Configuration.Sets();
    }

    /**
     * Create an instance of {@link Configuration.Transformers }
     * 
     */
    public Configuration.Transformers createConfigurationTransformers() {
        return new Configuration.Transformers();
    }

    /**
     * Create an instance of {@link Configuration.Formats }
     * 
     */
    public Configuration.Formats createConfigurationFormats() {
        return new Configuration.Formats();
    }

}
