//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.27 at 01:16:00 PM WEST 
//

package com.lyncode.xoai.dataprovider.xml.xoai;

import com.lyncode.xoai.dataprovider.exceptions.WritingXmlException;
import com.lyncode.xoai.dataprovider.xml.XMLWritable;
import com.lyncode.xoai.dataprovider.xml.XSISchema;
import com.lyncode.xoai.dataprovider.xml.XmlOutputContext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.stream.XMLStreamException;
import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.List;

import static com.lyncode.xoai.util.XmlIOUtils.writeElement;

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 *











 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"element"})
@XmlRootElement(name = "metadata")
public class Metadata implements XMLWritable {

    public static final String NAMESPACE_URI = "http://www.lyncode.com/xoai";
    public static final String SCHEMA_LOCATION = "http://www.lyncode.com/xsd/xoai.xsd";


    protected List<Element> element;

    /**
     * Gets the value of the element property.
     *
     *
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
      method for the element property.
     *
     *
     * For example, to add a new item, do as follows:
     *

     * getElement().add(newItem);

     *
     *
     *
     * Objects of the following type(s) are allowed in the list ;
     */
    public List<Element> getElement() {
        if (element == null) {
            element = new ArrayList<Element>();
        }
        return this.element;
    }

    @Override
    public void write(XmlOutputContext context) throws WritingXmlException {
        try {
            //String namespace = writter.getNamespaceContext().getNamespaceURI(XMLConstants.XMLNS_ATTRIBUTE);
            context.getWriter().writeStartElement("metadata");
            context.getWriter().writeDefaultNamespace(NAMESPACE_URI);
            context.getWriter().writeNamespace(XSISchema.PREFIX, XSISchema.NAMESPACE_URI);
            context.getWriter().writeAttribute(XSISchema.PREFIX, XSISchema.NAMESPACE_URI, "schemaLocation",
                    NAMESPACE_URI + " " + SCHEMA_LOCATION);

            for (Element elem : this.getElement()) {
                writeElement(context, "element", elem);
            }
            context.getWriter().writeEndElement();
            //writter.writeDefaultNamespace(namespace);
        } catch (XMLStreamException e) {
            throw new WritingXmlException(e);
        }

    }

    public String toString() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            this.write(XmlOutputContext.emptyContext(out));
        } catch (WritingXmlException e) {
            e.printStackTrace();
        } catch (XMLStreamException e) {
            e.printStackTrace();
        }
        return out.toString();
    }
}
