//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.14 at 01:23:41 AM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.lyncode.com/XOAIConfiguration")
package com.lyncode.xoai.dataprovider.xml.xoaidescription;

