//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.14 at 01:23:41 AM WEST 
//

package com.lyncode.xoai.dataprovider.xml.xoaidescription;

import javax.xml.bind.annotation.*;

/**
 *
 * Java class for XOAIDescription element declaration.
 * 
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 











 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "value" })
@XmlRootElement(name = "XOAIDescription")
public class XOAIDescription {

	@XmlValue
	protected String value;
	@XmlAttribute
	protected String type;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is ;
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is ;
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is ;
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is ;
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

}
